include("delivery/sh_config.lua")
include("delivery/sh_tanker_config.lua")
include("delivery/sh_tanker_job_config.lua")
include("delivery/cl_menu.lua")
include("delivery/cl_placer.lua")
include("delivery/cl_stock.lua")
include("delivery/cl_tanker.lua")
include("delivery/cl_tanker_placer.lua")
include("delivery/sh_rank_config.lua")
include("delivery/cl_rank_menu.lua")
include("delivery/cl_rank_placer.lua")
include("delivery/sh_express_config.lua")
include("delivery/cl_express_menu.lua")
include("delivery/cl_express_hud.lua")
include("delivery/cl_express_placer.lua")
include("delivery/sh_sewage_config.lua")
include("delivery/cl_sewage.lua")
include("delivery/cl_sewage_menu.lua")

print("[Delivery] Client loaded.")
