AddCSLuaFile("delivery/sh_config.lua")
AddCSLuaFile("delivery/sh_net.lua")
AddCSLuaFile("delivery/sh_tanker_config.lua")
AddCSLuaFile("delivery/sh_tanker_job_config.lua")
AddCSLuaFile("delivery/cl_menu.lua")
AddCSLuaFile("delivery/cl_placer.lua")
AddCSLuaFile("delivery/cl_stock.lua")
AddCSLuaFile("delivery/cl_tanker.lua")
AddCSLuaFile("delivery/cl_tanker_placer.lua")
AddCSLuaFile("delivery/sh_rank_config.lua")
AddCSLuaFile("delivery/cl_rank_menu.lua")
AddCSLuaFile("delivery/cl_rank_placer.lua")
AddCSLuaFile("delivery/sh_express_config.lua")
AddCSLuaFile("delivery/cl_express_menu.lua")
AddCSLuaFile("delivery/cl_express_hud.lua")
AddCSLuaFile("delivery/cl_express_placer.lua")
AddCSLuaFile("delivery/sh_sewage_config.lua")
AddCSLuaFile("delivery/sh_sewage_net.lua")
AddCSLuaFile("delivery/cl_sewage.lua")
AddCSLuaFile("delivery/cl_sewage_menu.lua")

-- Sewage entities
AddCSLuaFile("entities/sent_sewage_npc/shared.lua")
AddCSLuaFile("entities/sent_sewage_npc/cl_init.lua")
AddCSLuaFile("entities/sent_manhole/shared.lua")
AddCSLuaFile("entities/sent_manhole/cl_init.lua")
AddCSLuaFile("entities/sent_sewage_dropoff/shared.lua")
AddCSLuaFile("entities/sent_sewage_dropoff/cl_init.lua")

include("delivery/sh_config.lua")
include("delivery/sh_net.lua")
include("delivery/sh_tanker_config.lua")
include("delivery/sh_tanker_job_config.lua")
include("delivery/sv_database.lua")
include("delivery/sv_mapdata.lua")
include("delivery/sv_spawn.lua")
include("delivery/sv_stock.lua")
include("delivery/sv_tanker.lua")
include("delivery/sv_tanker_placer.lua")
include("delivery/sv_trade.lua")
include("delivery/sv_placer.lua")
include("delivery/sh_rank_config.lua")
include("delivery/sh_rank_net.lua")
include("delivery/sv_rank_database.lua")
include("delivery/sv_rank_mapdata.lua")
include("delivery/sv_rank_spawn.lua")
include("delivery/sv_rank_npc.lua")
include("delivery/sv_rank_placer.lua")
include("delivery/sh_express_config.lua")
include("delivery/sh_express_net.lua")
include("delivery/sv_express_database.lua")
include("delivery/sv_express.lua")
include("delivery/sv_express_placer.lua")
include("delivery/sh_sewage_config.lua")
include("delivery/sh_sewage_net.lua")
include("delivery/sv_sewage.lua")
include("delivery/sv_sewage_placer.lua")
include("autorun/server/sewage_entities.lua")

timer.Create("DeliveryCargoCleanup", 60, 0, function()
    for _, ent in ipairs(ents.FindByClass("sent_cargo")) do
        local owner = ent:GetNWEntity("CargoOwner")
        if not IsValid(owner) then
            ent:SetNWEntity("CargoOwner", NULL)
        end
    end
end)

print("[Delivery] System loaded.")
